### ISSUE TITLE
Camera Preview not straight

### ISSUE THREAD

**Issue by dipeshparashar** [AlexLittlejohn/ALCameraViewController#181] opened 2017-02-20 14:34 UTC
I've integrating ALCameraViewController via cocoapods and testing it on ipad. The camera view controller is not straight. Please look into it.

https://postimg.org/image/xx6gh1rrv/

**Comment by rocket-enterprise** [comment] 2017-03-19 00:23
I have the same Problem when using it with an iPad.

**Comment by rocket-enterprise** [comment] 2017-03-19 00:50
Ill found a Solution, change the createPreview function in CameraView.swift with the following:

  private func createPreview() {
        
        preview = AVCaptureVideoPreviewLayer(session: session)
        preview.videoGravity = AVLayerVideoGravityResizeAspectFill
        preview.frame = bounds
        
        switch UIApplication.shared.statusBarOrientation {
        case .portrait:
            preview?.connection.videoOrientation = AVCaptureVideoOrientation.portrait
            break
        case .portraitUpsideDown:
            preview?.connection.videoOrientation = AVCaptureVideoOrientation.portraitUpsideDown
            break
        case .landscapeRight:
            preview?.connection.videoOrientation = AVCaptureVideoOrientation.landscapeRight
            break
        case .landscapeLeft:
            preview?.connection.videoOrientation = AVCaptureVideoOrientation.landscapeLeft
            break
        default: break
        }

        layer.addSublayer(preview)
    }

The Problems seems that on first init the preview does not know the right orientation. Now it works fine

**Comment by AlexLittlejohn** [comment] 2017-09-08 08:35
Duplicate of #129, fixed in 2.0.2

**Closed by AlexLittlejohn** 2017-09-08 08:35 UTC
